### ISSUE TITLE
Support for private repo

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#105]
What if a repo named `myprivate` under `simonzhaoms` is private?
How to install the repo via `ml install`?

```console
$ ml install github:simonzhaoms/myprivate
```

It need to specify the SSH key in the SSH `config` or in other ways.

**Comment by simonzhaoms** [comment]
* To install a private repo:
   ```bash
   # Use a pre-configured SSH host
   ml install github@your_ssh_host:microsoft/cvbp

   # Or explicitly specify a SSH key file
   ml install microsoft/cvbp -i ~/.ssh/xxx_rsa
   ```

* To configure, you can
   1. Explicitly specify the SSH key file in the command:
      ```bash
      ml configure bpcv -i ~/.ssh/xxx_rsa
      ```
   1. Or use a pre-configured SSH host in MLHub.yaml:
      ```
      meta:                                                                                                                                                                         
        name: bpcv                                                                                                                                                         
      dependencies:                                                                                                                                                                 
        files:                                                                                                                                                                      
          - 'github@your_ssh_host:Microsoft/ComputerVision:utils_cv'                                                                                                                
      commands:                                                                                                                                                                     
        tag: Use pre-built model to tag an image.
      ```
      then run configure:
      ```bash
      ml configure bpcv
      ```
