### ISSUE TITLE
Support dependency tags in yaml

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#11]
As common patterns emerge for the configure.R file, identifying R packages that need to be installed. Handle the pattern in configure itself, rather than having the replicate the configure.R file for relevant packages. See configure.R for barchart and rain-tomorrow.

**Comment by gjwgit** [comment]
Dependencies are something like this in the yaml file:

```
  dependencies:
    R:
      cran: magrittr, dplyr=1.2.3, caret>4.5.6, e1017, shiny, shinyjs, V8, devtools, httr
      github: rstudio/tfruns, rstudio/reticulate, rstudio/keras
    py: tensorflow, keras, Image
```

If package dependency is not met, the mlhub will install into a model local folder.

**Comment by simonzhaoms** [comment]
How about?
```yaml
dependencies: 
  R: 
    cran: magrittr, dplyr=1.2.3, caret>4.5.6, e1017, httr  # All dependencies in one line
    github:  # One dependency per line
      - rstudio/tfruns 
      - rstudio/reticulate 
      - rstudio/keras 
  python:
    conda: environment.yaml  # Use conda to interpret dependencies
    pip:
      - pillow 
      - tools=1.1 
  files: 
    - https://zzz/config                     # File will be downloaded to the top level directory
    - https://zzz/def.csv: data/             # File has different path
    - https://zzz/ae0xe.png: images/cat.png  # File with different name
    - https://zzz/abc.zip: res/              # File needs to be uncompressed
    - https://zzz/xyz.zip: res/xyz.zip       # File doen't need to be uncompressed
```
