### ISSUE TITLE
INSTALL from github should install only the required files?

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#62]
Currently the whole github repo is downloaded. Would it make sens to just download HLHUB.yaml and README.md first, determine from HLHUB.yaml what other files are required? 

Use Case: pre-exisiting and quite large github repository that we only want to download mlhub required files.

**Comment by simonzhaoms** [comment]
Yes, that make sense.

**Comment by gjwgit** [comment]
Alternatively - does it make sense for the author to create a mlhub branch if I only wanted a subset of files? Which is an easier or more natural user experience?

**Comment by simonzhaoms** [comment]
What do you mean by a mlhub branch? @gjwgit

**Comment by gjwgit** [comment]
It did not make sense. I think the better user experience is for mlhub to determine what files need to be downloaded based on the MLHUB.yaml

**Comment by simonzhaoms** [comment]
What about?
```yaml
meta:
  ...
dependencies:
  ...
  files:   # Files not in the repo
    - https://zzz/abcd.png: images/cat.png
    - https://yyy/model.hdf5
pkgfiles:  # File inside the repo
  - MLHUB.yaml
  - script/demo.py
  - script/display.py
```
