### ISSUE TITLE
CONFIGURE support installing a local package

### ISSUE THREAD

**Issue by gjwgit** [mlhubber/mlhub#76]
For example, the movies repo currently requires a specific instance of the SAR package installed and is provided in the movies repo as SAR_0.0.1.tar.gz. Would like a mechanism in the MLHUB.yaml file to have this local tar file installed as in

`> install.packages("SAR_0.0.1.tar.gz", repos=NULL, lib=lib)`

Currently this is done in the remaining configure.R script.

**Comment by simonzhaoms** [comment]
it does support.  Please give it a try with a customized `MLHUB.yaml` 😎 
```yaml
--- # Movie Recommender
meta:
  name        : movies
  title       : Movie recommendation using the SAR algorthm.
  languages   : R
  keywords    : recommendation, R, SAR, movie recommendation
  modeller    : SAR
  type        : SAR local count
  version     : 2.0.1
  display     : display
  section     : ecommence, entertainment
  author      : Fang Zhou <zhouf@microsoft.com>
  maintainer  : Graham.Williams@togaware.com
  url         : https://github.com/gjwgit/movies
dependencies:
  cran: ggplot2, caret, plyr, dplyr
  R: deps/SAR_0.0.1.tar.gz  # Install specific local R package
  files:
    - data
    - data.R
    - demo.R
    - movie-recommender.R
    - print.R
    - README.md
    - sar_model.RData
    - score.R
    - train.R
    - SAR_0.0.1.tar.gz: deps/  # Place specific local R package into deps/
commands:
  demo     : Apply the model to a sample dataset.
```
```console
$ ml configure movies
...
...
*** R packages will be installed into '/home/simon/.mlhub/movies/R'

*** Installing specific R package 'deps/SAR_0.0.1.tar.gz' ...
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c make_similarity_matrix.cpp -o make_similarity_matrix.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c userpred.cpp -o userpred.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o SAR.so RcppExports.o make_similarity_matrix.o userpred.o -L/usr/lib/R/lib -lR
No man pages found in package  ‘SAR’ 

*** Downloading required files ...

To list all of the commands supported by the model:

  $ ml commands movies
```
