### ISSUE TITLE
CONFIGURE: Support for wildcard in `dependencies` -> `files` of MLHUB.yaml

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#78]
Instead of
```yaml
dependencies:
  files:
    - demo.R
    - print.R
    - display.R
    - score.R
```
we could
```yaml
dependencies:
  files:
    - *.R
```
