### ISSUE TITLE
MLHUB.yaml: Add support for file dependency to subfolder of a GitHub repo

### ISSUE THREAD

**Issue by simonzhaoms** [mlhubber/mlhub#87]
For example:

```yaml
dependencies:
  files:
    - 'mlhubber/mlhub@7fad23bdfdfjk:doc/': docs
```

This issue somehow is related to #62
